# -*- coding: utf-8 -*-
"""
Created on Sun Dec 11 12:34:10 2016

@author: MaVi
"""

dicNames = {'Acholeplasma laidlawii PG-8A': 'Bacteria',
 'Acidobacterium capsulatum ATCC 51196': 'Bacteria',
 'Aeropyrum pernix K1 DNA': 'Archaea',
 'Akkermansia muciniphila ATCC BAA-835': 'Bacteria',
 'Alicyclobacillus acidocaldarius subsp. acidocaldarius DSM 446 plasmid pAACI03': 'Bacteria',
 'Aquifex aeolicus VF5 plasmid ece1': 'Bacteria',
 'Archaeoglobus fulgidus DSM 4304': 'Archaea',
 'Archaeoglobus profundus DSM 5631 plasmid pArcpr01': 'Archaea',
 'Bacillus cereus Q1 plasmid pBc53': 'Bacteria',
 'Bacillus pseudofirmus OF4 plasmid pBpOF4-02': 'Bacteria',
 'Bacteroides fragilis YCH46 plasmid pBFY46 DNA': 'Bacteria',
 'Bdellovibrio bacteriovorus complete genome': 'Bacteria',
 'Bordetella pertussis strain Tohama I': 'Bacteria',
 'Borrelia burgdorferi B31 plasmid lp56': 'Bacteria',
 'Caldivirga maquilingensis IC-167': 'Archaea',
 'Campylobacter jejuni subsp. jejuni 81-176 plasmid pVir': 'Bacteria',
 'Candidatus Amoebophilus asiaticus 5a2': 'Bacteria',
 'Carboxydothermus hydrogenoformans Z-2901': 'Bacteria',
 'Cenarchaeum symbiosum A': 'Archaea',
 'Chlamydia trachomatis strain L2/434/Bu complete genome': 'Bacteria',
 'Chlorobium chlorochromatii CaD3': 'Bacteria',
 'Chloroflexus aurantiacus J-10-fl': 'Bacteria',
 'Clostridium acetobutylicum ATCC 824 megaplasmid pSOL1': 'Bacteria',
 'Corynebacterium glutamicum ATCC 13032 DNA': 'Bacteria',
 'Coxiella burnetii RSA 493 plasmid pQpH1': 'Bacteria',
 'Cyanothece sp. ATCC 51142 plasmid D': 'Bacteria',
 'Deinococcus radiodurans R1 plasmid MP1': 'Bacteria',
 'Desulfurococcus kamchatkensis 1221n': 'Archaea',
 'Dictyoglomus thermophilum H-6-12': 'Bacteria',
 'Elusimicrobium minutum Pei191': 'Bacteria',
 'Fibrobacter succinogenes subsp. succinogenes S85': 'Bacteria',
 'Flavobacterium psychrophilum JIP02/86 complete genome': 'Bacteria',
 'Gemmatimonas aurantiaca T-27 DNA': 'Bacteria',
 'Gloeobacter violaceus PCC 7421 DNA': 'Bacteria',
 'Haloarcula marismortui ATCC 43049 plasmid pNG700': 'Archaea',
 'Halomicrobium mukohataei DSM 12286 plasmid pHmuk01': 'Archaea',
 'Haloquadratum walsbyi DSM 16790 plasmid PL47 complete genome': 'Archaea',
 'Halorhabdus utahensis DSM 12940': 'Archaea',
 'Halorubrum lacusprofundi ATCC 49239 plasmid pHLAC01': 'Archaea',
 'Haloterrigena turkmenica DSM 5511 plasmid pHTUR06': 'Archaea',
 'Hyperthermus butylicus DSM 5456': 'Archaea',
 'Ignicoccus hospitalis KIN4/I': 'Archaea',
 'Magnetococcus marinus MC-1': 'Bacteria',
 'Metallosphaera sedula DSM 5348': 'Archaea',
 'Methanobrevibacter ruminantium M1': 'Archaea',
 'Methanocaldococcus fervens AG86 plasmid pMEFER01': 'Archaea',
 'Methanocella paludicola SANAE DNA': 'Archaea',
 'Methanococcoides burtonii DSM 6242': 'Archaea',
 'Methanococcus aeolicus Nankai-3': 'Archaea',
 'Methanococcus maripaludis C6': 'Archaea',
 'Methanococcus vannielii SB': 'Archaea',
 'Methanocorpusculum labreanum Z': 'Archaea',
 'Methanoculleus marisnigri JR1': 'Archaea',
 'Methanopyrus kandleri AV19': 'Archaea',
 'Methanosaeta thermophila PT': 'Archaea',
 'Methanosarcina acetivorans str. C2A': 'Archaea',
 'Methanosarcina mazei strain Goe1': 'Archaea',
 'Methanosphaera stadtmanae DSM 3091': 'Archaea',
 'Methanospirillum hungatei JF-1': 'Archaea',
 'Methylacidiphilum infernorum V4': 'Bacteria',
 'Mycoplasma genitalium G37 strain G-37 unique_12': 'Bacteria',
 'Nanoarchaeum equitans Kin4-M': 'Archaea',
 'Natronomonas pharaonis DSM 2160 plasmid PL23 complete genome': 'Archaea',
 'Nitrosopumilus maritimus SCM1': 'Archaea',
 'Nostoc punctiforme PCC 73102 plasmid pNPUN05': 'Bacteria',
 'Opitutus terrae PB90-1': 'Bacteria',
 'Pedobacter heparinus DSM 2366': 'Bacteria',
 'Picrophilus torridus DSM 9790': 'Archaea',
 'Pirellula staleyi DSM 6068': 'Bacteria',
 'Prochlorococcus marinus str. AS9601': 'Bacteria',
 'Psychrobacter arcticus 273-4': 'Bacteria',
 'Pyrobaculum aerophilum str. IM2': 'Archaea',
 'Pyrobaculum arsenaticum DSM 13514': 'Archaea',
 'Pyrococcus abyssi GE5 plasmid pGT5': 'Archaea',
 'Pyrococcus furiosus DSM 3638': 'Archaea',
 'Pyrococcus horikoshii OT3 DNA': 'Archaea',
 'Rhizobium leguminosarum bv. trifolii WSM1325 plasmid pR132505': 'Bacteria',
 'Rhodopirellula baltica SH 1 complete genome': 'Bacteria',
 'Rhodospirillum rubrum ATCC 11170 plasmid': 'Bacteria',
 'Rickettsia rickettsii str. Iowa': 'Bacteria',
 'Shewanella putrefaciens CN-32': 'Bacteria',
 'Staphylothermus marinus F1': 'Archaea',
 'Sulfolobus acidocaldarius DSM 639': 'Archaea',
 'Sulfolobus solfataricus P2': 'Archaea',
 'Synechococcus elongatus PCC 6301 DNA': 'Bacteria',
 'Thermanaerovibrio acidaminovorans DSM 6589': 'Bacteria',
 'Thermobaculum terrenum ATCC BAA-798 chromosome 2': 'Bacteria',
 'Thermococcus gammatolerans EJ3': 'Archaea',
 'Thermodesulfovibrio yellowstonii DSM 11347': 'Bacteria',
 'Thermofilum pendens Hrk 5 plasmid pTPEN01': 'Archaea',
 'Thermomicrobium roseum DSM 5159 plasmid': 'Bacteria',
 'Thermoplasma acidophilum DSM 1728 complete genome': 'Archaea',
 'Thermoplasma volcanium GSS1 DNA': 'Archaea',
 'Thermotoga maritima MSB8': 'Bacteria',
 'Thermus thermophilus HB8 plasmid pTT8 DNA': 'Bacteria'}